buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.+'
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

apply plugin: 'java'
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

version = '1.1'
group = 'fr.shoqapik'

base {
    archivesName = 'noelytramod-1.20.1'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            arg '-mixin.config=noelytramod.mixins.json'
            mods {
                noelytrasmod { source sourceSets.main }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            arg '-mixin.config=noelytramod.mixins.json'
            mods {
                noelytrasmod { source sourceSets.main }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'noelytramod.mixins.refmap.json'
    config 'noelytramod.mixins.json'
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : 'noelytrasmod',
            'Specification-Vendor'  : 'shoqapik',
            'Specification-Version' : '1',
            'Implementation-Title'  : project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor' : 'shoqapik',
            'MixinConfigs'          : 'noelytramod.mixins.json'
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
