modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="noelytrasmod"
version="1.1"
displayName="Sorry but the Elytra is in another End City"
logoFile="icon.png"
credits="Programmed by shoqapik12 & Art by Zenokim"
authors="precisemodpacker"
description="Replaces the Elytra in End City ships with a configurable item. Fixes LootR compatibility."

[[dependencies.noelytrasmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.noelytrasmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
