modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="noelytrasmod"
version="2.0.0"
displayName="Sorry but the Elytra is in another End City"
logoFile="icon.png"
credits="Programmed by shoqapik12 & Art by Zenokim"
authors="precisemodpacker"
description="Replaces the Elytra in End City ships with a configurable item. Fixes LootR compatibility."

[[dependencies.noelytrasmod]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.noelytrasmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
